version: "{build}"

# Source Config
clone_folder: C:\projects\phonedata

# Build host

environment:
  GOPATH: c:\gopath

stack: go 1.14

build: false
deploy: false

install:
  - go get -u github.com/jstemmer/go-junit-report
  - go get -u golang.org/x/lint/golint

before_test:
  - go vet ./...

test_script:
  - go version
  - go env
  - go test -race -v -count=1 -coverpkg=./... -test.short -coverprofile=coverage.out -timeout=10s `go list ./... | grep -v /vendor/` 2>&1 | c:\gopath\bin\go-junit-report > tests_report.xml

on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests_report.xml))

notifications:
  - provider: Email
    to:
      - 614422099@qq.com
    subject: '[phonedata] win build'
    message: 新的编译信息
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
