name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go vet ./...

    - name: Install dependencies
      run: make install

    - name: Go Test
      run: make test

    - name: Codeclimate
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./test-reporter
        chmod +x ./test-reporter
        ./test-reporter before-build
        go test -coverprofile c.out `go list ./... | grep -v /vendor/` -v -count=1 -coverpkg=./...
        sed -i "s/github.com\/wechaty\/go-wechaty\///g" c.out
        ./test-reporter format-coverage -t gocov --prefix wechaty
        ./test-reporter upload-coverage

    - name: Build
      run: go build -o ding-dong -v ./examples/ding-dong-bot.go
